package pages.hotel.footer.support;

import org.openqa.selenium.WebDriver;
import static commons.CommonHotelURL.*;
import static constants.hotel.contentPage.ConstPrivacyPageEN.*;
import static interfaces.hotel.footer.support.PrivacyPolicyPageUI.*;

import commons.hotel.CommonHotelPages;
public class PrivacyPolicyPage extends CommonHotelPages {
  WebDriver driver;

  public PrivacyPolicyPage(WebDriver driver_) {
    this.driver = driver_;
    super.setDriver(driver);
  }

  public void verifyContentPage() {
    String[] titlePrivacy = {PRIVACY_SUB_TITLE1, PRIVACY_SUB_TITLE2, PRIVACY_SUB_TITLE3, PRIVACY_SUB_TITLE4,
      PRIVACY_SUB_TITLE5, PRIVACY_SUB_TITLE6, PRIVACY_SUB_TITLE7, PRIVACY_SUB_TITLE8, PRIVACY_SUB_TITLE9, PRIVACY_SUB_TITLE10,
      PRIVACY_SUB_TITLE11, PRIVACY_SUB_TITLE12, PRIVACY_SUB_TITLE13, PRIVACY_SUB_TITLE14, PRIVACY_SUB_TITLE15, PRIVACY_SUB_TITLE16};
    String[] contentPrivacy = {PRIVACY_CONTENT8, PRIVACY_CONTENT9, PRIVACY_CONTENT10, PRIVACY_CONTENT11, PRIVACY_CONTENT10,
      PRIVACY_CONTENT11, PRIVACY_CONTENT12, PRIVACY_CONTENT13, PRIVACY_CONTENT14, PRIVACY_CONTENT15, PRIVACY_CONTENT16,
      PRIVACY_CONTENT17, PRIVACY_CONTENT18, PRIVACY_CONTENT19, PRIVACY_CONTENT20, PRIVACY_CONTENT21, PRIVACY_CONTENT22,
      PRIVACY_CONTENT23, PRIVACY_CONTENT24, PRIVACY_CONTENT25, PRIVACY_CONTENT26, PRIVACY_CONTENT27, PRIVACY_CONTENT28,
      PRIVACY_CONTENT29, PRIVACY_CONTENT30, PRIVACY_CONTENT31, PRIVACY_CONTENT32, PRIVACY_CONTENT33, PRIVACY_CONTENT34,
      PRIVACY_CONTENT34, PRIVACY_CONTENT35, PRIVACY_CONTENT36, PRIVACY_CONTENT37, PRIVACY_CONTENT38, PRIVACY_CONTENT39,
      PRIVACY_CONTENT50, PRIVACY_CONTENT51, PRIVACY_CONTENT52, PRIVACY_CONTENT53, PRIVACY_CONTENT54,
      PRIVACY_CONTENT55, PRIVACY_CONTENT56, PRIVACY_CONTENT57, PRIVACY_CONTENT58, PRIVACY_CONTENT59,
      PRIVACY_CONTENT40, PRIVACY_CONTENT41, PRIVACY_CONTENT42, PRIVACY_CONTENT43, PRIVACY_CONTENT44, PRIVACY_CONTENT45,
      PRIVACY_CONTENT46, PRIVACY_CONTENT47, PRIVACY_CONTENT48, PRIVACY_CONTENT49};
    String[] subContentPrivacy = {PRIVACY_SUB_CONTENT1, PRIVACY_SUB_CONTENT2, PRIVACY_SUB_CONTENT3, PRIVACY_SUB_CONTENT4, PRIVACY_SUB_CONTENT5, PRIVACY_SUB_CONTENT6,
      PRIVACY_SUB_CONTENT7, PRIVACY_SUB_CONTENT8, PRIVACY_SUB_CONTENT9, PRIVACY_SUB_CONTENT10, PRIVACY_SUB_CONTENT11, PRIVACY_SUB_CONTENT10,
      PRIVACY_SUB_CONTENT11, PRIVACY_SUB_CONTENT12, PRIVACY_SUB_CONTENT13, PRIVACY_SUB_CONTENT14, PRIVACY_SUB_CONTENT15, PRIVACY_SUB_CONTENT16,
      PRIVACY_SUB_CONTENT17, PRIVACY_SUB_CONTENT18, PRIVACY_SUB_CONTENT19, PRIVACY_SUB_CONTENT20, PRIVACY_SUB_CONTENT21, PRIVACY_SUB_CONTENT22,
      PRIVACY_SUB_CONTENT23, PRIVACY_SUB_CONTENT24, PRIVACY_SUB_CONTENT25, PRIVACY_SUB_CONTENT26, PRIVACY_SUB_CONTENT27, PRIVACY_SUB_CONTENT28,
      PRIVACY_SUB_CONTENT29, PRIVACY_SUB_CONTENT30, PRIVACY_SUB_CONTENT31, PRIVACY_SUB_CONTENT32, PRIVACY_SUB_CONTENT33, PRIVACY_SUB_CONTENT34, PRIVACY_SUB_CONTENT35};
    boolean title = compareTwoListByConst(titlePrivacy, PRIVACY_SUB_TITLE_LIST);
    if (!title) {
      System.out.println("Title Privacy Policy page wrong! ");
    }
    boolean content = compareTwoListByConst(contentPrivacy, PRIVACY_CONTENT_LIST);
    if (!content) {
      System.out.println("Content Privacy Policy page wrong! ");
    }
    boolean subContent = compareTwoListByConst(subContentPrivacy, PRIVACY_SUB_CONTENT_LIST);
    if (!subContent) {
      System.out.println("Sub Content Privacy Policy page wrong! ");
    }
    if (title && content && subContent) {
      System.out.println("Privacy Policy page correct! ");
    }
  }
}

