package pages.hotel.footer.useful;

import org.openqa.selenium.WebDriver;

import static interfaces.hotel.footer.useful.BinaceTravelPageUI.*;

import commons.hotel.CommonHotelPages;
public class BinaceTravelPage extends CommonHotelPages {
  WebDriver driver;

  public BinaceTravelPage(WebDriver driver_) {
    this.driver = driver_;
    super.setDriver(driver);
  }
  public boolean verifyBannerBinanceTravel() {
    boolean check = true;
    String[] content = {"BINANCE_TRAVEL_BANNER", "BINANCE_TRAVEL_SUB_BANNER", "MY_WISH_LIST_HOTEL", "BINANCE_TRAVEL_HOME_LINK","BINANCE_TRAVEL_SEARCH_BTN",
      "LandingPage_CustomerSupport", "LandingPage_CustomerSupport_Content", "MENU_BestPrice", "LandingPage_BestPriceGuarantee_Content",
      "LandingPage_MultiPaymentOption", "LandingPage_MultiPaymentOption_Content", "LandingPage_RealValueRewards", "LandingPage_RealValueRewards_Content"};
    String[] xpath = {BINANCE_TRAVEL_BANNER, BINANCE_TRAVEL_SUB_BANNER, BINANCE_TRAVEL_HOTEL_LINK, BINANCE_TRAVEL_SEARCH_BTN, BINANCE_TRAVEL_CUSTOMER_SUPPORT_TITLE,
      BINANCE_TRAVEL_CUSTOMER_SUPPORT_CONTENT, BINANCE_TRAVEL_BEST_PRICE_TITLE, BINANCE_TRAVEL_BEST_PRICE_CONTENT, BINANCE_TRAVEL_PAYMENT_OPTION_TITLE,
      BINANCE_TRAVEL_PAYMENT_OPTION_CONTENT, BINANCE_TRAVEL_REWARDS_TITLE, BINANCE_TRAVEL_REWARDS_CONTENT};
    return   verifyTwoListByKey(content, xpath);
  }
  public boolean verifyNorthAmerica() {
    boolean check = true;
    String[] content = {"BINANCE_PAGE_CHOOSE_YOUR", "BINANCE_TRAVEL_EUROPE", "BINANCE_TRAVEL_NORTH", "BINANCE_TRAVEL_ASIA","BINANCE_TRAVEL_AMERICAN",
      "BINANCE_TRAVEL_OCEAN", "BINANCE_TRAVEL_SOUTH_AMERICAN", "BINANCE_TRAVEL_AFRICA", "BINANCE_TRAVEL_MIDDLE",
      "BINANCE_TRAVEL_NEW_YORK", "BINANCE_TRAVEL_ANGELES_SUB","BINANCE_TRAVEL_ANGELES", "BINANCE_TRAVEL_ANGELES_SUB", "BINANCE_TRAVEL_VANCOUVER", "BINANCE_TRAVEL_VANCOUVER_SUB"};
    String[] xpath = {BINANCE_PAGE_CHOOSE_YOUR, BINANCE_TRAVEL_EUROPE, BINANCE_TRAVEL_NORTH, BINANCE_TRAVEL_ASIA, BINANCE_TRAVEL_AMERICAN,
      BINANCE_TRAVEL_OCEAN, BINANCE_TRAVEL_SOUTH_AMERICAN, BINANCE_TRAVEL_AFRICA, BINANCE_TRAVEL_MIDDLE,
      BINANCE_TRAVEL_NEW_YORK, BINANCE_TRAVEL_NEW_YORK_SUB, BINANCE_TRAVEL_ANGELES,BINANCE_TRAVEL_ANGELES_SUB,BINANCE_TRAVEL_VANCOUVER,BINANCE_TRAVEL_VANCOUVER_SUB};
    return   verifyTwoListByKey(content, xpath);
  }
  public boolean verifyStartPrice() {
    boolean check = true;
    String[] content = {"BINANCE_PAGE_CHOOSE_YOUR", "BINANCE_TRAVEL_EUROPE", "BINANCE_TRAVEL_NORTH", "BINANCE_TRAVEL_ASIA","BINANCE_TRAVEL_AMERICAN",
      "BINANCE_TRAVEL_OCEAN", "BINANCE_TRAVEL_SOUTH_AMERICAN", "BINANCE_TRAVEL_AFRICA", "BINANCE_TRAVEL_MIDDLE",
      "BINANCE_TRAVEL_NEW_YORK", "BINANCE_TRAVEL_ANGELES_SUB","BINANCE_TRAVEL_ANGELES", "BINANCE_TRAVEL_ANGELES_SUB", "BINANCE_TRAVEL_VANCOUVER", "BINANCE_TRAVEL_VANCOUVER_SUB"};
    String[] xpath = {BINANCE_PAGE_CHOOSE_YOUR, BINANCE_TRAVEL_EUROPE, BINANCE_TRAVEL_NORTH, BINANCE_TRAVEL_ASIA, BINANCE_TRAVEL_AMERICAN,
      BINANCE_TRAVEL_OCEAN, BINANCE_TRAVEL_SOUTH_AMERICAN, BINANCE_TRAVEL_AFRICA, BINANCE_TRAVEL_MIDDLE,
      BINANCE_TRAVEL_NEW_YORK, BINANCE_TRAVEL_NEW_YORK_SUB, BINANCE_TRAVEL_ANGELES,BINANCE_TRAVEL_ANGELES_SUB,BINANCE_TRAVEL_VANCOUVER,BINANCE_TRAVEL_VANCOUVER_SUB};
    return   verifyTwoListByKey(content, xpath);
  }

  public boolean verifyTopCountryBinance() {
    boolean check = true;
    String[] content = {"BINANCE_PAGE_DISCOVER", "BINANCE_TRAVEL_SINGAPORE", "BINANCE_TRAVEL_JAPAN", "BINANCE_TRAVEL_INDONESIA","BINANCE_TRAVEL_THAILAND"};
    String[] xpath = {BINANCE_PAGE_DISCOVER, BINANCE_TRAVEL_SINGAPORE, BINANCE_TRAVEL_JAPAN, BINANCE_TRAVEL_INDONESIA, BINANCE_TRAVEL_THAILAND};
    return   verifyTwoListByKey(content, xpath);
  }
}
