package pages.hotel.footer.travala;

import org.openqa.selenium.WebDriver;


import commons.hotel.CommonHotelPages;

import static commons.CommonHotelURL.PRICE_GUARANTEE_PATH;
import static commons.CommonHotelURL.*;
import static interfaces.hotel.footer.travala.PriceGuaranteePageUI.*;

public class PriceGuaranteePage extends CommonHotelPages {
  WebDriver driver;
  boolean status = true;

  public PriceGuaranteePage(WebDriver driver_) {
    this.driver = driver_;
    super.setDriver(driver);
  }

  public boolean verifyPriceGuarantee() {
    String[] content = {"MENU_BestPrice", "PRICE_GUARANTEE_HOW_IT_WORK", "PRICE_GUARANTEE_HOW_IT_WORK_CONTENT", "PRICE_GUARANTEE_CHECKLIST", "PRICE_GUARANTEE_CHECKLIST_CONTENT1",
      "PRICE_GUARANTEE_CHECKLIST_CONTENT2", "PRICE_GUARANTEE_CHECKLIST_CONTENT3", "PRICE_GUARANTEE_CHECKLIST_CONTENT4", "PRICE_GUARANTEE_MAKE_CLAIM",
      "PRICE_GUARANTEE_MAKE_CLAIM_CONTENT1", "PRICE_GUARANTEE_MAKE_CLAIM_CONTENT2", "PRICE_GUARANTEE_MAKE_CLAIM_CONTENT3", "PRICE_GUARANTEE_HOW_MAKE_CLAIM",
      "PRICE_GUARANTEE_HOW_MAKE_CLAIM_CONTENT", "PRICE_GUARANTEE_HOW_MAKE_CLAIM_CONTENT1", "PRICE_GUARANTEE_HOW_MAKE_CLAIM_CONTENT2", "PRICE_GUARANTEE_HOW_MAKE_CLAIM_CONTENT3",
      "PRICE_GUARANTEE_HOW_MAKE_CLAIM_CONTENT4", "PRICE_GUARANTEE_HOW_MAKE_CLAIM_CONTENT5", "PRICE_GUARANTEE_TERM", "PRICE_GUARANTEE_TERM_CONTENT", "PRICE_GUARANTEE_TERM_CONTENT1",
      "PRICE_GUARANTEE_TERM_CONTENT2", "PRICE_GUARANTEE_TERM_CONTENT3", "PRICE_GUARANTEE_TERM_CONTENT4", "PRICE_GUARANTEE_TERM_CONTENT5", "PRICE_GUARANTEE_TERM_CONTENT6",
      "PRICE_GUARANTEE_TERM_CONTENT7", "PRICE_GUARANTEE_TERM_CONTENT8", "PRICE_GUARANTEE_TERM_CONTENT9", "PRICE_GUARANTEE_TERM_CONTENT10", "PRICE_GUARANTEE_TERM_CONTENT11"};
    String[] xpath = {PRICE_GUARANTEE_TILTE, PRICE_GUARANTEE_HOW_IT_WORK, PRICE_GUARANTEE_HOW_IT_WORK_CONTENT, PRICE_GUARANTEE_CHECKLIST, PRICE_GUARANTEE_CHECKLIST_CONTENT1,
      PRICE_GUARANTEE_CHECKLIST_CONTENT2, PRICE_GUARANTEE_CHECKLIST_CONTENT3, PRICE_GUARANTEE_CHECKLIST_CONTENT4, PRICE_GUARANTEE_MAKE_CLAIM, PRICE_GUARANTEE_MAKE_CLAIM_CONTENT1,
      PRICE_GUARANTEE_MAKE_CLAIM_CONTENT2, PRICE_GUARANTEE_MAKE_CLAIM_CONTENT3, PRICE_GUARANTEE_HOW_CLAIM, PRICE_GUARANTEE_HOW_CLAIM_CONTENT, PRICE_GUARANTEE_HOW_CLAIM_CONTENT1,
      PRICE_GUARANTEE_HOW_CLAIM_CONTENT2, PRICE_GUARANTEE_HOW_CLAIM_CONTENT3, PRICE_GUARANTEE_HOW_CLAIM_CONTENT4, PRICE_GUARANTEE_HOW_CLAIM_CONTENT5, PRICE_GUARANTEE_TERM,
      PRICE_GUARANTEE_TERM_CONTENT, PRICE_GUARANTEE_TERM_CONTENT1, PRICE_GUARANTEE_TERM_CONTENT2, PRICE_GUARANTEE_TERM_CONTENT3, PRICE_GUARANTEE_TERM_CONTENT4,
      PRICE_GUARANTEE_TERM_CONTENT5, PRICE_GUARANTEE_TERM_CONTENT6, PRICE_GUARANTEE_TERM_CONTENT7, PRICE_GUARANTEE_TERM_CONTENT8, PRICE_GUARANTEE_TERM_CONTENT9,
      PRICE_GUARANTEE_TERM_CONTENT10, PRICE_GUARANTEE_TERM_CONTENT11};
    status = verifyUrlPage(PRICE_GUARANTEE_PATH) && verifyTwoListByKey(content, xpath) && verifyMenuStaticPage();
    return status;
  }
}
