package pages.hotel.footer.travala;

import org.openqa.selenium.WebDriver;

import commons.hotel.CommonHotelPages;
import static interfaces.hotel.footer.travala.SmartTermPageUI.*;
public class SmartTermPage extends CommonHotelPages {
  WebDriver driver;
  boolean check = true;

  public SmartTermPage(WebDriver driver_) {
    this.driver = driver_;
    super.setDriver(driver);
  }

  public void verifyTextOnPage() {
    String[] titleExp = {"SMART_TERM_TITLE1", "SMART_TERM_TITLE2", "SMART_TERM_TITLE3"
      , "SMART_TERM_TITLE4", "SMART_TERM_TITLE5", "SMART_TERM_TITLE6", "SMART_TERM_TITLE7", "SMART_TERM_TITLE8", "SMART_TERM_TITLE9"};
    boolean title = compareTwoListByKey(titleExp, SMART_TERM_TITLE);
    if (!title) {
      System.out.println("Title Term Smart Wrong");
    }
    String[] titleContentExp = {"SMART_TERM_CONTENT1", "SMART_TERM_CONTENT2", "SMART_TERM_CONTENT3", "SMART_TERM_CONTENT4", "SMART_TERM_CONTENT5", "SMART_TERM_CONTENT6"
      , "SMART_TERM_CONTENT7", "SMART_TERM_CONTENT8", "SMART_TERM_CONTENT9", "SMART_TERM_CONTENT10", "SMART_TERM_CONTENT11", "SMART_TERM_CONTENT12"
      , "SMART_TERM_CONTENT13", "SMART_TERM_CONTENT14", "SMART_TERM_CONTENT16", "SMART_TERM_CONTENT17", "SMART_TERM_CONTENT18", "SMART_TERM_CONTENT19"
      , "SMART_TERM_CONTENT20", "SMART_TERM_CONTENT21", "SMART_TERM_CONTENT22", "SMART_TERM_CONTENT23", "SMART_TERM_CONTENT24", "SMART_TERM_CONTENT26"
      , "SMART_TERM_CONTENT27", "SMART_TERM_CONTENT28", "SMART_TERM_CONTENT29", "SMART_TERM_CONTENT30", "SMART_TERM_CONTENT31", "SMART_TERM_CONTENT32"
      , "SMART_TERM_CONTENT33", "SMART_TERM_CONTENT34", "SMART_TERM_CONTENT36", "SMART_TERM_CONTENT37", "SMART_TERM_CONTENT38", "SMART_TERM_CONTENT39"
      , "SMART_TERM_CONTENT40", "SMART_TERM_CONTENT41", "SMART_TERM_CONTENT42", "SMART_TERM_CONTENT43", "SMART_TERM_CONTENT44", "SMART_TERM_CONTENT46"
      , "SMART_TERM_CONTENT47", "SMART_TERM_CONTENT48", "SMART_TERM_CONTENT49", "SMART_TERM_CONTENT50", "SMART_TERM_CONTENT51", "SMART_TERM_CONTENT52"
      , "SMART_TERM_CONTENT53", "SMART_TERM_CONTENT54", "SMART_TERM_CONTENT56", "SMART_TERM_CONTENT57", "SMART_TERM_CONTENT58", "SMART_TERM_CONTENT59"
      , "SMART_TERM_CONTENT60", "SMART_TERM_CONTENT61", "SMART_TERM_CONTENT62", "SMART_TERM_CONTENT63", "SMART_TERM_CONTENT64", "SMART_TERM_CONTENT66",
      "SMART_TERM_CONTENT67", "SMART_TERM_CONTENT68", "SMART_TERM_CONTENT69", "SMART_TERM_CONTENT70", "SMART_TERM_CONTENT71", "SMART_TERM_CONTENT72",
      "SMART_TERM_CONTENT73", "SMART_TERM_CONTENT74", "SMART_TERM_CONTENT76", "SMART_TERM_CONTENT77", "SMART_TERM_CONTENT78", "SMART_TERM_CONTENT79"
      , "SMART_TERM_CONTENT80", "SMART_TERM_CONTENT81", "SMART_TERM_CONTENT82", "SMART_TERM_CONTENT83", "SMART_TERM_CONTENT84", "SMART_TERM_CONTENT86"
      , "SMART_TERM_CONTENT87", "SMART_TERM_CONTENT88", "SMART_TERM_CONTENT89", "SMART_TERM_CONTENT90", "SMART_TERM_CONTENT91", "SMART_TERM_CONTENT92"
      , "SMART_TERM_CONTENT93", "SMART_TERM_CONTENT94", "SMART_TERM_CONTENT96", "SMART_TERM_CONTENT97", "SMART_TERM_CONTENT98", "SMART_TERM_CONTENT99"
      , "SMART_TERM_CONTENT100", "SMART_TERM_CONTENT101", "SMART_TERM_CONTENT102", "SMART_TERM_CONTENT103", "SMART_TERM_CONTENT104", "SMART_TERM_CONTENT105",
      "SMART_TERM_CONTENT106", "SMART_TERM_CONTENT107", "SMART_TERM_CONTENT108", "SMART_TERM_CONTENT109", "SMART_TERM_CONTENT110", "SMART_TERM_CONTENT111",
      "SMART_TERM_CONTENT112", "SMART_TERM_CONTENT113", "SMART_TERM_CONTENT114"};
    boolean titleContent = compareTwoListByKey(titleContentExp, SMART_TERM_CONTENT);
    if (!titleContent) {
      System.out.println(" Content Term Smart Wrong");
    }
    if (! title && titleContent) {
      System.out.println("Text at smart term wrong");
    } else {
      System.out.println("Text at smart term correct");
    }
  }


}
