package pages.hotel.footer.travala;

import org.openqa.selenium.WebDriver;
import commons.hotel.CommonHotelPages;
import static interfaces.hotel.footer.travala.TravelGiftCardPageUI.*;

public class TravelGiftCardPage extends CommonHotelPages {
  WebDriver driver;

  public TravelGiftCardPage(WebDriver driver_) {
    this.driver = driver_;
    super.setDriver(driver);
  }

  public boolean verifyTravelGiftCardPage() {
    String[] content = {"TRAVEL_GIFT_CARD_TITLE", "TRAVEL_GIFT_CARD_BANNER", "TRAVEL_GIFT_CARD_BANNER1", "TRAVEL_GIFT_CARD_MAIN_CONTENT", "TRAVEL_GIFT_CARD_EASY_BUY", "TRAVEL_GIFT_CARD_EASY_BUY_CONTENT",
      "TRAVEL_GIFT_CARD_EASY_USE", "TRAVEL_GIFT_CARD_EASY_USE_CONTENT", "TRAVEL_GIFT_CARD_NO_EXPIRATION", "TRAVEL_GIFT_CARD_NO_EXPIRATION_CONTENT", "TRAVEL_GIFT_CARD_FAQ",
      "HELP_COMMON_QUESTION10", "TRAVEL_GIFT_CARD_QUESTION1_CONTENT1", "TRAVEL_GIFT_CARD_QUESTION1_CONTENT2",
      "TRAVEL_GIFT_CARD_QUESTION1_STEP1", "TRAVEL_GIFT_CARD_QUESTION1_STEP2", "TRAVEL_GIFT_CARD_QUESTION1_STEP3", "TRAVEL_GIFT_CARD_QUESTION1_STEP4", "TRAVEL_GIFT_CARD_QUESTION1_STEP5",
      "TRAVEL_GIFT_CARD_FAQ_NOTE", "TRAVEL_GIFT_CARD_NOTE1", "TRAVEL_GIFT_CARD_NOTE2",
      "TRAVEL_GIFT_CARD_QUESTION2", "TRAVEL_GIFT_CARD_QUESTION2_CONTENT1", "TRAVEL_GIFT_CARD_QUESTION2_CONTENT2",
      "TRAVEL_GIFT_CARD_QUESTION2_STEP1", "TRAVEL_GIFT_CARD_QUESTION2_STEP2", "TRAVEL_GIFT_CARD_QUESTION2_STEP3", "TRAVEL_GIFT_CARD_QUESTION2_STEP4", "TRAVEL_GIFT_CARD_QUESTION2_CONTENT",
      "TRAVEL_GIFT_CARD_TERM", "TRAVEL_GIFT_CARD_TERM_CONTENT", "TRAVEL_GIFT_CARD_BUY_TGC_BTN", "TRAVEL_GIFT_CARD_BUY_TGC_TEXT", "TRAVEL_GIFT_CARD_BUY_TGC_LINK"};
    String[] xpath = {TRAVEL_GIFT_CARDS_TITLE, TRAVEL_GIFT_CARDS_BANNER, TRAVEL_GIFT_CARDS_BANNER1, TRAVEL_GIFT_CARD_MAIN_CONTENT, TRAVEL_GIFT_CARDS_EASY_BUY, TRAVEL_GIFT_CARDS_EASY_BUY_CONTENT,
      TRAVEL_GIFT_CARDS_EASY_USE, TRAVEL_GIFT_CARDS_EASY_USE_CONTENT, TRAVEL_GIFT_CARDS_EXPIRATION, TRAVEL_GIFT_CARDS_EXPIRATION_CONTENT, TRAVEL_GIFT_CARDS_FAQ,
      TRAVEL_GIFT_CARD_QUESTION1, TRAVEL_GIFT_CARD_QUESTION1_CONTENT1, TRAVEL_GIFT_CARD_QUESTION1_CONTENT2,
      TRAVEL_GIFT_CARD_QUESTION1_STEP1, TRAVEL_GIFT_CARD_QUESTION1_STEP2, TRAVEL_GIFT_CARD_QUESTION1_STEP3, TRAVEL_GIFT_CARD_QUESTION1_STEP4, TRAVEL_GIFT_CARD_QUESTION1_STEP5,
      TRAVEL_GIFT_CARD_FAQ_NOTE, TRAVEL_GIFT_CARD_NOTE1, TRAVEL_GIFT_CARD_NOTE2,
      TRAVEL_GIFT_CARD_QUESTION2, TRAVEL_GIFT_CARD_QUESTION2_CONTENT1, TRAVEL_GIFT_CARD_QUESTION2_CONTENT2,
      TRAVEL_GIFT_CARD_QUESTION2_STEP1, TRAVEL_GIFT_CARD_QUESTION2_STEP2, TRAVEL_GIFT_CARD_QUESTION2_STEP3, TRAVEL_GIFT_CARD_QUESTION2_STEP4, TRAVEL_GIFT_CARD_QUESTION2_CONTENT,
      TRAVEL_GIFT_CARD_TERM, TRAVEL_GIFT_CARD_TERM_CONTENT, TRAVEL_GIFT_CARD_BUY_TGC_BTN, TRAVEL_GIFT_CARD_TEXT, TRAVEL_GIFT_CARD_REDEEM_LINK};
    return verifyTwoListByKey(content, xpath);
  }

  public BuyGiftCardPage clickToBuyGiftCardLink() {
    clickToElementByJavascript(driver, TRAVEL_GIFT_CARD_BUY_GIFT_CARD_LINK);
    return new BuyGiftCardPage(driver);
  }

}
