package constants.hotel.contentCoinPage;

public class ConstSFundPageEN {
  public static final String CONST_SFUND_FULL_NAME = "Seedify.fund (SFUND)";
  public static final String CONST_SFUND_WHAT_IS_TITLE = "What is Seedify.fund?";
  public static final String CONST_SFUND_WHAT_IS_CONTENT = "Seedify is one of the most prominent blockchain gaming-focused Incubator and Launchpad ecosystems, empowering innovators and project developers through access to funding, community and partnership building and a complete support system to help drive the future of gaming and blockchain. Most recently, Seedify has announced its new platform, the Seedify NFT Space, a marketplace focused on in-game and metaverse items.  SFUND Is Seedify’s ecosystem native token, based on Binance Smart Chain. With SFUND, holders can participate in the IGOs hosted at Seedify (after completing KYC and Staking or Farming their SFUNDs) and also stake or farm the SFUND to earn passive income. Seedify will keep adding more utility to its token through constant innovation and the launch of new products related to the Blockchain Gaming.";
  public static final String CONST_SFUND_MISSION_CONTENT = "Seedify‘s mission is to redefine the blockchain gaming environment by empowering lives through play-to-earn revenue models by providing the best Launchpad and Incubation platform to gaming projects and, by launchings these projects to the community via the IGOs (Initial Gaming Offering). They aim to bring millions of new users to blockchain while creating many new jobs, financial benefits, as well as increasing the adoption rate of blockchain drastically.";

  public static final String CONST_SFUND_USE_CASE_CONTENT1 = "Invest SFUND in order to get guaranteed access to launchpad allocations from token sale events. Seedify Launchpad is the third and final part of a project's journey in our ecosystem.  The first part is: seed funding -> where projects get their initial funding.  The second part is: incubation -> where projects get stronger through the support systems driven by community involvement program and solution partners program.  And the third part is: launchpad -> where projects can launch their IDO events and sell their tokens for funding before market release.  While Seedify Launchpad is the third of this journey in our ecosystem, projects who only want to use the Launchpad part without prior seed funding and incubation, can do so by applying.";
  public static final String CONST_SFUND_USE_CASE_CONTENT2 = "Vote on decisions and the direction of proposed projects and innovative ideas.";
  public static final String CONST_SFUND_USE_CASE_CONTENT3 = "SFUND can be utilized for a number of different purchases and at Travala.com, it can be used to book over 3,000,000 travel products, including hotels, homes, flights, and activities. With accommodation in over 230 countries and territories, 600+ airlines, and more than 400,000 activities, Travala.com’s selection provides travelers with extensive choice when booking with SFUND.";
  public static final String CONST_SFUND_USE_CASE_CONTENT4 ="This staking and farming mechanisms are critical aspects to give additional financial benefits for our token holders, as well as to create a skin in the game approach for our community to research the projects thoroughly in their selection processes and involve in the Seedify Involvement programs more, since the financial gains on these rewards will be highly correlated with the projects’ strengths when they get released to the market, as well as how successful these projects become throughout their journey. Seedify locked staking have 5 lock period options with different APYs: 7 days - 5% APY 14 days -11% APY 30 days - 25% APY 60 days - 55% APY 90 days - 75% APY";

  public static final String CONST_SFUND_USE_CASE_CONTENT5 ="The inventors receive SFUND tokens as rewards when they submit their projects in Seedifyand successfully get their seed fund. SFUND supports the experts who invest and are involved in the Seedify DeFi system through rewards.";

   public static final String CONST_SFUND_TEAM_ITEM_TITLE1 = "LEVENT CEM AYDAN";
  public static final String CONST_SFUND_TEAM_ITEM_POSITION1 = "CEO";
  public static final String CONST_SFUND_TEAM_ITEM_DES1 = "Levent Cem Aydan is CEO of Seedify.fund. He has ten years of entrepreneurial experience and started showing interest in the blockchain ecosystem in 2012. In 2021, he founded Seedify.fund to allow game players to vote on decisions and the direction of proposed projects and innovative ideas.  Seedify has now over 35 team members working on various areas of expertise, like Marketing, Business Development, 3D Designers, UX Designers, Developers, QA Managers, and many other professionals that allow Seedify to have solid growth in the market.";

  public static final String CONST_SFUND_FAQ_CONTENT1 = "The Seedify platform provides and supervises Initial Game Offerings (IGOs), supports pioneering blockchain games, ensures project funding, helps to build a community of gamers, and creates a marketing strategy. Thus, the Seedify community has the opportunity to receive tokens for nascent games before they are listed on exchanges.";
  public static final String CONST_SFUND_FAQ_CONTENT2 = "In the Seedify.fund ecosystem, functions and mechanisms interact as a whole, supporting each other and offering benefits for all parties in the process. The main products are: funding pool, incubator, community involvement programs, community involvement rewards, staking, launchpad, yield farming, and the solution partners program.";
  public static final String CONST_SFUND_FAQ_CONTENT3 = "Here is the step by step journey for staking $SFUND tokens:  1. Enter Seedify Staking Platform. 2. Connect your wallet by clicking on the ‘Connect Wallet’ button in the top right corner. (If you’re using a wallet dApp browser, your wallet may automatically connect). Double-check that you’re accessing the right web page prior to connecting your wallet — https://staking.seedify.fund/ 3. Select ‘Stake’. 4. Select the length of time you wish to lock your SFUND tokens for, from 7, 14, 30, 60 or 90 days. 5. Click the ‘Approve’ button and confirm. 6. Click on the ‘Stake’ button. 7. Enter the amount you wish to stake. 8. Click the ‘Confirm’ button, then confirm the transaction. 9. Enjoy watching your SFUND rewards grow!  If you want to keep track of your staking rewards, you can use this amazing tool created by the Seedify HODLers, it’s an SFUND LP/Staking Rewards Calculator: https://seedifyhodlers.com/tools/calculator/";


   public static final String CONST_SFUND_FAQ_TITLE1 = "What makes Seedify.fund unique?";
  public static final String CONST_SFUND_FAQ_TITLE2 = "What are the main products of the Seedify.fund ecosystem?";
  public static final String CONST_SFUND_FAQ_TITLE3 = "How can I stake SFUND?";



}
