package constants.hotel.contentNFT;

public class NFTTermCondition {

  public static final String BUY_CONST_NFT_NOT_LOGIN_POPUP_CONTENT = "Oops! Looks like you haven't log in to your Travala account.";
  public static final String CONST_NFT_FAQ_TITLE1 = "What is Travala NFT?";
  public static final String CONST_NFT_FAQ_TITLE2 = "When can I buy Travala NFT?";
  public static final String CONST_NFT_FAQ_TITLE3 = "What is the price of Travala NFT";
  public static final String CONST_NFT_FAQ_TITLE4 = "How many can I buy?";
  public static final String CONST_NFT_FAQ_CONTENT1 = "";
  public static final String CONST_NFT_FAQ_CONTENT2 = "";
  public static final String CONST_NFT_FAQ_CONTENT3 = "";
  public static final String CONST_NFT_FAQ_CONTENT4 = "";
  public static final String CONST_NFT_HOW_IT_WORK_SUB_TITLE1 = "";
  public static final String CONST_NFT_HOW_IT_WORK_SUB_TITLE2 = "";
  public static final String CONST_NFT_HOW_IT_WORK_SUB_TITLE3 = "";
  public static final String CONST_NFT_HOW_IT_WORK_SUB_TITLE4 = "";
  public static final String CONST_NFT_HOW_IT_WORK_SUB_CONTENT1 = "";
  public static final String CONST_NFT_HOW_IT_WORK_SUB_CONTENT2 = "";
  public static final String CONST_NFT_HOW_IT_WORK_SUB_CONTENT3 = "";
  public static final String CONST_NFT_HOW_IT_WORK_SUB_CONTENT4 = "";
  public static final String CONST_NFT_BENEFIT_TITLE1 = "Passive Income";
  public static final String CONST_NFT_BENEFIT_TITLE2 = "Voting Rights";
  public static final String CONST_NFT_BENEFIT_TITLE3 = "TRVL Airdrops";
  public static final String CONST_NFT_BENEFIT_TITLE4 = "Unique NFT Avatar";
  public static final String CONST_NFT_BENEFIT_TITLE5 = "Loyalty Rewards";
  public static final String CONST_NFT_BENEFIT_TITLE6 = "AVA Payment";
  public static final String CONST_NFT_BENEFIT_TITLE7 = "Proof of Travel";
  public static final String CONST_NFT_BENEFIT_TITLE8 = "Concierge Access";
  public static final String CONST_NFT_BENEFIT_TITLE9 = "Metaverses";
  public static final String CONST_NFT_BENEFIT_TITLE10 = "";
  public static final String CONST_NFT_BENEFIT_DESC1 = "";
  public static final String CONST_NFT_BENEFIT_DESC2 = "";
  public static final String CONST_NFT_BENEFIT_DESC3 = "";
  public static final String CONST_NFT_BENEFIT_DESC4 = "";
  public static final String CONST_NFT_BENEFIT_DESC5 = "";
  public static final String CONST_NFT_BENEFIT_DESC6 = "";
  public static final String CONST_NFT_BENEFIT_DESC7 = "";
  public static final String CONST_NFT_BENEFIT_DESC8 = "";
  public static final String CONST_NFT_BENEFIT_DESC9 = "";
  public static final String CONST_NFT_BENEFIT_DESC10 = "";
  public static final String CONST_NFT_BANNER_TITLE = "";
  public static final String CONST_NFT_BANNER_SUB_TITLE = "";
  public static final String CONST_NFT_WHAT_IS_CONST_NFT_TITLE = "";
  public static final String CONST_NFT_WHAT_IS_CONST_NFT_CONTENT = "";
  public static final String CONST_NFT_BENEFIT_TITLE = "";
  public static final String CONST_NFT_BENEFIT_CONTENT = "";
  public static final String CONST_NFT_COLLECTION_TITLE = "";
  public static final String CONST_NFT_HOW_IT_WORK_TITLE = "";
  public static final String CONST_NFT_FREQUENTLY_TITLE = "";
}
